import { VxeGridPropTypes } from 'vxe-table';

export const getColumns = (): VxeGridPropTypes.Columns => {
	return [
		{ type: 'checkbox', width: 40, fixed: 'left', align: 'center' },
		{
			type: 'expand',
			field: 'expand',
			width: 60,
			fixed: 'left',
			slots: { content: 'expand-expand' },
			align: 'center',
		},
		{ title: '订柜号', field: 'bookingNo', minWidth: 140, fixed: 'left' },
		{ title: '货物状态', field: 'cargoStatus', minWidth: 100, fixed: 'left' },
		{ title: '柜型', field: 'containerType', minWidth: 80 },
		{ title: '运输路径', field: 'route', minWidth: 150 },
		{ title: 'SO', field: 'soNo', minWidth: 150 },
		{ title: '柜号', field: 'containerNo', minWidth: 150 },
		{ title: '订阅错误信息', field: 'errorInfoYdSummary', minWidth: 300 },
		{ title: '封签号', field: 'sealNo', minWidth: 180 },
		{ title: '船公司', field: 'shippingLine', minWidth: 180 },
		{ title: '航线', field: 'shippingRoute', minWidth: 180 },
		{ title: '船名', field: 'vessel', minWidth: 180 },
		{ title: '航次', field: 'voyage', minWidth: 180 },
		{ title: '拖车报关服务商', field: 'truckCustomsAgent', minWidth: 180 },
		{ title: '运输方式', field: 'transportMode', minWidth: 180 },
		{ title: '国际运输服务商', field: 'intlCarrier', minWidth: 180 },
		{ title: '清关服务商', field: 'customsClearance', minWidth: 180 },
		{ title: '提货派送服务商', field: 'lastMileDelivery', minWidth: 180 },
		{ title: '起始港', field: 'originPort', minWidth: 180 },
		{ title: '目的港', field: 'destPort', minWidth: 180 },
		{ title: '国家', field: 'country', minWidth: 180 },
		{ title: '第一目的仓', field: 'firstWarehouse', minWidth: 180 },
		{
			title: '第二目的仓',
			field: 'secondWarehouse',
			minWidth: 220,
			slots: { default: 'secondWarehouse' },
		},
		{
			title: '总体积',
			field: 'totalVolume',
			minWidth: 180,
			slots: { default: 'totalVolume' },
		},
		{
			title: '总毛重',
			field: 'totalGrossWeight',
			minWidth: 180,
			slots: { default: 'totalGrossWeight' },
		},
		{
			title: '总净重',
			field: 'totalNetWeight',
			minWidth: 180,
			slots: { default: 'totalNetWeight' },
		},
		{ title: '提空柜时间', field: 'emptyContainerPickupTime', minWidth: 180 },
		{ title: '物流实际装柜时间', field: 'loadingTime', minWidth: 180 },
		{ title: '截单时间', field: 'cutoffTime', minWidth: 180 },
		{ title: '还重时间', field: 'fullContainerReturnTime', minWidth: 180 },
		{ title: '截关时间', field: 'customCutoffTime', minWidth: 180 },
		{ title: '装船时间', field: 'shippingTime', minWidth: 180 },
		{
			title: '开船时间',
			field: 'actualDepartureTime',
			minWidth: 300,
			slots: { default: 'actualDepartureTime' },
		},
		{
			title: '到港时间',
			field: 'actualArrivalTime',
			minWidth: 300,
			slots: { default: 'actualArrivalTime' },
		},
		{
			title: '入库时间（第一目的仓）',
			field: 'actualInboundTimeFirst',
			minWidth: 350,
			slots: { default: 'actualInboundTimeFirst' },
		},
		{ title: '调拨单号', field: 'transferOrderNo', minWidth: 180 },
		{
			title: '三方仓入库单号',
			field: 'thirdWarehouseInboundNo',
			minWidth: 180,
		},
		{ title: '卸船时间', field: 'dischargingTime', minWidth: 180 },
		{
			title: '抵达交货地PDAR',
			field: 'arrivalAtDeliveryLocationTime',
			minWidth: 180,
		},
		{
			title: '交货地卸箱PDDS',
			field: 'unloadingAtDeliveryLocationTime',
			minWidth: 180,
		},
		{ title: '是否可提箱', field: 'availableFlag', minWidth: 180 },
		{ title: '可提柜时间', field: 'availableDate', minWidth: 180 },
		{ title: '提柜时间', field: 'appointmentDate', minWidth: 180 },
		{ title: 'Last free day', field: 'lastFreeDay', minWidth: 180 },
		{ title: '是否滞留', field: 'holdsFlag', minWidth: 180 },
		{ title: '海关放行状态', field: 'customsStatus', minWidth: 180 },
		{ title: '滞期费', field: 'demurrage', minWidth: 180 },
		{ title: '还空箱时间', field: 'emptyContainerReturnTime', minWidth: 180 },
		{ title: '到仓时间', field: 'warehouseArrivalTime', minWidth: 180 },
		{ title: '入库时间', field: 'inboundTime', minWidth: 180 },
		{
			title: '中转时间',
			field: 'tsLoadingTime',
			minWidth: 400,
			slots: { default: 'tsLoadingTime' },
		},
		{ title: '开船是否准时', field: 'departureOntimeFlag', minWidth: 180 },
		{ title: '到港是否准时', field: 'arrivalOntimeFlag', minWidth: 180 },
		{ title: '提柜是否准时', field: 'pickupOntimeFlag', minWidth: 180 },
		{ title: '还空是否准时', field: 'returnEmptyOntimeFlag', minWidth: 180 },
		{ title: '创建时间', field: 'createTime', minWidth: 180, sortable: true },
		{ title: '修改时间', field: 'updateTime', minWidth: 180 },
		{
			title: '操作',
			field: 'action',
			width: 150,
			fixed: 'right',
			slots: { default: 'action' },
		},
	];
};
