import { useI18n } from 'vue-i18n';

export const getColumns = () => {
	const { t } = useI18n();
	return [
		{
			type: 'checkbox',
			width: 60,
			fixed: 'left',
		},
		{
			title: t('店铺/站点'),
			field: 'storeName',
			width: 160,
			fixed: 'left',
		},
		{
			title: t('SKU/产品名称'),
			field: 'skuCode',
			width: 300,
			fixed: 'left',
		},
		{
			title: t('图片'),
			field: 'imgUrl',
			width: 100,
			fixed: 'left',
		},
		{
			title: t('商品ID'),
			field: 'itemId',
			width: 150,
			fixed: 'left',
			showHeaderTooltip: true,
			headerTooltip: t('取自于ItemID'),
		},
		{
			title: t('MSKU'),
			field: 'msku',
			width: 200,
		},
		{
			title: t('GTIN'),
			field: 'gtin',
			width: 140,
		},
		{
			title: t('是否发布'),
			field: 'publishingStatus',
			width: 120,
		},
		{
			title: t('可售'),
			field: 'availableUnits',
			width: 120,
			showHeaderTooltip: true,
			headerTooltip: t('可售库存'),
			isSum: true,
		},
		{
			title: t('拒收（损坏）'),
			field: 'damagedReceipts',
			width: 180,
			showHeaderTooltip: true,
			headerTooltip: t('损坏未记录库存'),
			isSum: true,
		},
		{
			title: t('入库量'),
			field: 'inboundUnits',
			width: 120,
			sortable: true,
			isSum: true,
		},
		{
			title: t('库容'),
			field: 'cubeUsed',
			width: 120,
			sortable: true,
			isSum: true,
		},
		{
			title: t('首次到库日期'),
			field: 'firstInStockDate',
			width: 160,
			sortable: true,
		},
		{
			title: t('可供销售天数'),
			field: 'daysOfSupply',
			width: 140,
			sortable: true,
			isSum: true,
		},
		{
			title: t('近一年预测量'),
			field: 'forecastYear',
			width: 200,
			showHeaderTooltip: true,
			headerTooltip: t('沃尔玛平台预测'),
			isSum: true,
		},
		{
			title: t('近一个月预测量'),
			field: 'forecastMonth',
			width: 200,
			showHeaderTooltip: true,
			headerTooltip: t('沃尔玛平台预测'),
			isSum: true,
		},
		{
			title: t('平台建议补货量'),
			field: 'platformSuggestedReplenishment',
			width: 160,
			sortable: true,
			isSum: true,
		},
		{
			title: t('库存削减建议'),
			field: 'surplusUnits',
			width: 160,
			sortable: true,
			isSum: true,
		},
		{
			title: t('售罄率'),
			field: 'sellThroughRate',
			width: 120,
			showHeaderTooltip: true,
			headerTooltip: t('特定时期内销量占总供给量的百分比'),
			isSum: true,
		},
		{
			title: t('平台销售状态'),
			field: 'publishingStatusPlatform',
			width: 140,
		},
		{
			title: t('商品生命周期阶段'),
			field: 'itemLifecycle',
			width: 180,
			sortable: true,
		},
		{
			title: t('平台库存状态'),
			field: 'status',
			width: 140,
		},
		{
			title: t('不可售库存数量'),
			field: 'unavailableUnits',
			width: 160,
			sortable: true,
			isSum: true,
		},
		{
			title: t('近30天入库量'),
			field: 'last30DaysUnitsReceived',
			width: 140,
			sortable: true,
			isSum: true,
		},
		{
			title: t('近30天货件申报量'),
			field: 'last30DaysPoUnits',
			width: 180,
			sortable: true,
			isSum: true,
		},
		{
			title: t('预计缺货日期'),
			field: 'predictedOutOfStockDate',
			width: 160,
			sortable: true,
		},
		{
			title: t('近7天销售量'),
			field: 'last7DaysUnitsSales',
			width: 140,
			sortable: true,
			isSum: true,
		},
		{
			title: t('近7天销售额'),
			field: 'last7DaysSales',
			width: 140,
			sortable: true,
			isSum: true,
		},
		{
			title: t('近七天有库存天数'),
			field: 'last7DaysInstockDays',
			width: 160,
			sortable: true,
			isSum: true,
		},
		{
			title: t('近30天销售量'),
			field: 'last30DaysUnitsSales',
			width: 140,
			sortable: true,
			isSum: true,
		},
		{
			title: t('近30天销售额'),
			field: 'last30DaysSales',
			width: 160,
			sortable: true,
			isSum: true,
		},
		{
			title: t('近30天有库存天数'),
			field: 'last30DaysInstockDays',
			width: 180,
			sortable: true,
			isSum: true,
		},
		{
			title: t('0~90'),
			field: 'ats0To90Days',
			width: 100,
			sortable: true,
			isSum: true,
		},
		{
			title: t('91~180'),
			field: 'ats91To180Days',
			width: 100,
			sortable: true,
			isSum: true,
		},
		{
			title: t('181~270'),
			field: 'ats181To270Days',
			width: 110,
			sortable: true,
			isSum: true,
		},
		{
			title: t('271~365'),
			field: 'ats271To365Days',
			width: 110,
			sortable: true,
			isSum: true,
		},
		{
			title: t('365+'),
			field: 'ats365PlusDays',
			width: 100,
			sortable: true,
			isSum: true,
		},
	];
};
