import type { Columns } from '/@/types/table';

export const columns: Columns = [
	{ title: '平台', field: 'platformChannelCodeText', width: 140 },
	{ title: '站点', field: 'siteCodeText', width: 140 },
	{ title: '店铺', field: 'storeIdText', width: 120 },
	{ title: '币种', field: 'currencyText', width: 120 },
	{ title: 'Order ID', field: 'orderId', width: 160 },
	{ title: 'Order Status', field: 'orderStatus', width: 140 },
	{
		title: 'Cancelation/Return Type',
		field: 'cancelationReturnType',
		width: 220,
	},
	{ title: 'Normal or Pre-order', field: 'normalOrPreOrder', width: 160 },
	{ title: 'SKU ID', field: 'skuId', width: 140 },
	{ title: 'Seller SKU', field: 'sellerSku', width: 140 },
	{ title: 'Product Name', field: 'productName', width: 200 },
	{ title: 'Variation', field: 'variation', width: 200 },
	{ title: 'Quantity', field: 'quantity', width: 120, align: 'right' },
	{
		title: 'Sku Quantity of return',
		field: 'skuQuantityOfReturn',
		width: 180,
		align: 'right',
	},
	{
		title: 'SKU Unit Original Price',
		field: 'skuUnitOriginalPrice',
		width: 180,
		align: 'right',
	},
	{
		title: 'SKU Subtotal Before Discount',
		field: 'skuSubtotalBeforeDiscount',
		width: 220,
		align: 'right',
	},
	{
		title: 'SKU Platform Discount',
		field: 'skuPlatformDiscount',
		width: 180,
		align: 'right',
	},
	{
		title: 'SKU Seller Discount',
		field: 'skuSellerDiscount',
		width: 180,
		align: 'right',
	},
	{
		title: 'SKU Subtotal After Discount',
		field: 'skuSubtotalAfterDiscount',
		width: 220,
		align: 'right',
	},
	{
		title: 'Shipping Fee After Discount',
		field: 'shippingFeeAfterDiscount',
		width: 220,
		align: 'right',
	},
	{
		title: 'Original Shipping Fee',
		field: 'originalShippingFee',
		width: 180,
		align: 'right',
	},
	{
		title: 'Shipping Fee Seller Discount',
		field: 'shippingFeeSellerDiscount',
		width: 220,
		align: 'right',
	},
	{
		title: 'Co-Funded Shipping Fee Discount',
		field: 'coFundedShippingFeeDiscount',
		width: 260,
		align: 'right',
	},
	{
		title: 'Shipping Fee Platform Discount',
		field: 'shippingFeePlatformDiscount',
		width: 240,
		align: 'right',
	},
	{
		title: 'Payment platform discount',
		field: 'paymentPlatformDiscount',
		width: 220,
		align: 'right',
	},
	{
		title: 'Retail Delivery Fee',
		field: 'retailDeliveryFee',
		width: 180,
		align: 'right',
	},
	{ title: 'Taxes', field: 'taxes', width: 140, align: 'right' },
	{ title: 'Order Amount', field: 'orderAmount', width: 160, align: 'right' },
	{
		title: 'Order Refund Amount',
		field: 'orderRefundAmount',
		width: 200,
		align: 'right',
	},
	{ title: 'Created Time', field: 'createdTime', width: 180 },
	{ title: 'Paid Time', field: 'paidTime', width: 180 },
	{ title: 'RTS Time', field: 'rtsTime', width: 180 },
	{ title: 'Shipped Time', field: 'shippedTime', width: 180 },
	{ title: 'Delivered Time', field: 'deliveredTime', width: 180 },
	{ title: 'Cancelled Time', field: 'cancelledTime', width: 180 },
	{ title: 'Cancel By', field: 'cancelBy', width: 160 },
	{ title: 'Cancel Reason', field: 'cancelReason', width: 200 },
	{ title: 'Fulfillment Type', field: 'fulfillmentType', width: 180 },
	{ title: 'Warehouse Name', field: 'warehouseName', width: 200 },
	{ title: 'Tracking ID', field: 'trackingId', width: 180 },
	{ title: 'Delivery Option Type', field: 'deliveryOptionType', width: 200 },
	{ title: 'Delivery Option', field: 'deliveryOption', width: 200 },
	{
		title: 'Shipping Provider Name',
		field: 'shippingProviderName',
		width: 220,
	},
	{ title: 'Buyer Message', field: 'buyerMessage', width: 200 },
	{ title: 'Buyer Username', field: 'buyerUsername', width: 180 },
	{ title: 'Recipient', field: 'sellerName', width: 180 },
	{ title: 'Phone #', field: 'recipientPhone', width: 160 },
	{ title: 'Country', field: 'country', width: 140 },
	{ title: 'State', field: 'state', width: 140 },
	{ title: 'City', field: 'city', width: 140 },
	{ title: 'Zipcode', field: 'zipcode', width: 140 },
	{ title: 'Address Line 1', field: 'addressLine1', width: 200 },
	{ title: 'Address Line 2', field: 'addressLine2', width: 200 },
	{ title: 'Delivery Instruction', field: 'deliveryInstruction', width: 200 },
	{ title: 'Payment Method', field: 'paymentMethod', width: 160 },
	{ title: 'Weight(kg)', field: 'weightKg', width: 160, align: 'right' },
	{ title: 'Product Category', field: 'productCategory', width: 200 },
	{ title: 'Package ID', field: 'packageId', width: 180 },
	{ title: 'Seller Note', field: 'sellerNote', width: 200 },
	{ title: 'Shipping Information', field: 'addressId', width: 200 },
	{ title: 'Combined Listing', field: 'combinedListing', width: 200 },
];
