import { useI18n } from 'vue-i18n';

export const getColumns = () => {
	const { t } = useI18n();
	return [
		{
			type: 'checkbox',
			width: 60,
			fixed: 'left',
		},
		{
			title: t('SKU/产品名称'),
			field: 'skuCode',
			width: 300,
			align: 'left',
			fixed: 'left',
		},
		{
			title: t('国家'),
			field: 'countryCode',
			width: 100,
			align: 'center',
			fixed: 'left',
		},
		{
			title: t('平台渠道'),
			field: 'platformChannelCode',
			width: 120,
			align: 'center',
			fixed: 'left',
		},
		{
			title: t('采购在途'),
			field: 'purchaseOnWay',
			width: 120,
			align: 'center',
			isSum: true,
		},
		{
			title: t('平台仓库存'),
			field: 'platformWarehouseInventory',
			width: 120,
			align: 'center',
			isSum: true,
		},
		{
			title: t('三方仓库存'),
			field: 'thirdWarehouseInventory',
			width: 120,
			align: 'center',
			isSum: true,
		},
		{
			title: t('在库库存'),
			field: 'inStockInventory',
			width: 120,
			align: 'center',
			isSum: true,
			showHeaderTooltip: true,
			headerTooltip: t('=平台仓在库+三方仓在库'),
		},
		{
			title: t('在途库存'),
			field: 'onWayInventory',
			width: 120,
			align: 'center',
			isSum: true,
			showHeaderTooltip: true,
			headerTooltip: t('=平台仓在途+三方仓在途'),
		},
		{
			title: t('账面库存'),
			field: 'bookInventory',
			width: 120,
			align: 'center',
			isSum: true,
			showHeaderTooltip: true,
			headerTooltip: t('=在库库存+在途库存'),
		},
		{
			title: t('总库存'),
			field: 'totalInventory',
			width: 120,
			align: 'center',
			isSum: true,
			showHeaderTooltip: true,
			headerTooltip: t('=账面库存+采购在途'),
		},
		{
			title: t('在库可售天数'),
			field: 'inStockSalesDays',
			width: 140,
			align: 'center',
			isSum: true,
			showHeaderTooltip: true,
			headerTooltip: t('=在库库存/加权日销'),
		},
		{
			title: t('在途可售天数'),
			field: 'onWaySalesDays',
			width: 140,
			align: 'center',
			isSum: true,
			showHeaderTooltip: true,
			headerTooltip: t('=在途库存/加权日销'),
		},
		{
			title: t('账面可售天数'),
			field: 'bookSalesDays',
			width: 140,
			align: 'center',
			isSum: true,
			showHeaderTooltip: true,
			headerTooltip: t('=账面库存/加权日销'),
		},
		{
			title: t('采购在途可售天数'),
			field: 'purchaseOnWaySalesDays',
			width: 160,
			align: 'center',
			isSum: true,
			showHeaderTooltip: true,
			headerTooltip: t('=采购在途/加权日销'),
		},
		{
			title: t('总库存可售天数'),
			field: 'totalSalesDays',
			width: 150,
			align: 'center',
			isSum: true,
			showHeaderTooltip: true,
			headerTooltip: t('=总库存/加权日销'),
		},
		{
			title: t('近30天销量'),
			field: 'salesLast30Days',
			width: 130,
			align: 'center',
			isSum: true,
		},
		{
			title: t('近14天销量'),
			field: 'salesLast14Days',
			width: 130,
			align: 'center',
			isSum: true,
		},
		{
			title: t('近7天销量'),
			field: 'salesLast7Days',
			width: 130,
			align: 'center',
			isSum: true,
		},
		{
			title: t('加权日销'),
			field: 'weightedDailySales',
			width: 120,
			align: 'center',
			isSum: true,
			precision: 'decimal',
			showHeaderTooltip: true,
			headerTooltip: t(
				'近30天销量/30*30%+近14天销量/14*30%+近7天销量/7*40%+0.01'
			),
		},
	];
};
