// Element Plus 表格列配置接口
import type { TableColumn } from '@/types/table/table';

export const list: TableColumn[] = [
	{
		prop: 'selection',
		label: '选择',
		width: 60,
		align: 'center',
		type: 'selection',
		isShow: false,
	},
	{
		prop: 'platformChannelCode',
		label: '平台',
		width: 100,
		align: 'center',
		valueType: 'text',
	},
	{
		prop: 'siteCode',
		label: '站点',
		width: 100,
		align: 'center',
		valueType: 'text',
	},
	{
		prop: 'storeName',
		label: '店铺',
		width: 150,
		align: 'center',
		valueType: 'text',
	},
	{
		prop: 'orderNo',
		label: '订单号',
		width: 180,
		align: 'center',
		valueType: 'text',
	},
	{
		prop: 'fulfillmentStatus',
		label: '履约状态',
		width: 120,
		align: 'center',
		valueType: 'text',
	},
	{
		prop: 'orderTime',
		label: '订单时间',
		width: 180,
		align: 'center',
		valueType: 'text',
	},
	{
		prop: 'skuCode',
		label: 'SKU',
		width: 150,
		align: 'center',
		valueType: 'text',
	},
	{
		prop: 'mskuCode',
		label: 'MSKU',
		width: 200,
		align: 'center',
		valueType: 'text',
	},
	{
		prop: 'quantity',
		label: '数量',
		width: 100,
		align: 'center',
		valueType: 'number',
	},
	{
		prop: 'productRevenue',
		label: '商品收入',
		width: 120,
		align: 'center',
		valueType: 'number',
	},
	{
		prop: 'tipRevenue',
		label: 'Tip',
		width: 100,
		align: 'center',
		valueType: 'number',
	},
	{
		prop: 'postalInsFee',
		label: '运费险-邮包',
		width: 120,
		align: 'center',
		valueType: 'number',
	},
	{
		prop: 'extendedInsFee',
		label: '运费险-延保',
		width: 120,
		align: 'center',
		valueType: 'number',
	},
	{
		prop: 'discount',
		label: '折扣',
		width: 120,
		align: 'center',
		valueType: 'number',
	},
	{
		prop: 'shipping',
		label: '运费',
		width: 120,
		align: 'center',
		valueType: 'number',
	},
	{
		prop: 'refund',
		label: '退款',
		width: 120,
		align: 'center',
		valueType: 'number',
	},
	{
		prop: 'currency',
		label: '币种',
		width: 120,
		align: 'center',
		valueType: 'text',
	},
	{
		prop: 'updateTime',
		label: '生成时间',
		width: 180,
		align: 'center',
		valueType: 'text',
	},
];

// 模拟数据
export const mockData = [
	{
		reportId: 1,
		platformChannelCode: 'Shopify',
		storeId: 1001,
		siteCode: 'US',
		storeName: 'MERACH Official Store',
		orderNo: 'SH2026010801',
		fulfillmentStatus: 'fulfilled',
		orderTime: '2026-01-08 10:30:00',
		skuCode: 'MR-2494P1-US',
		mskuCode: 'MSKU-2494P1',
		quantity: 2,
		productRevenue: 299.99,
		tipRevenue: 5.0,
		postalInsFee: 3.5,
		extendedInsFee: 2.0,
		discount: 20.0,
		shipping: 15.0,
		refund: 0,
		currency: 'USD',
		createTime: '2026-01-08 10:35:00',
	},
	{
		reportId: 2,
		platformChannelCode: 'Shopify',
		storeId: 1002,
		siteCode: 'UK',
		storeName: 'MERACH UK Store',
		orderNo: 'SH2026010802',
		fulfillmentStatus: 'pending',
		orderTime: '2026-01-08 11:15:00',
		skuCode: 'MR-3589B2-UK',
		mskuCode: 'MSKU-3589B2',
		quantity: 1,
		productRevenue: 450.0,
		tipRevenue: 0,
		postalInsFee: 5.0,
		extendedInsFee: 3.0,
		discount: 50.0,
		shipping: 20.0,
		refund: 0,
		currency: 'GBP',
		createTime: '2026-01-08 11:20:00',
	},
	{
		reportId: 3,
		platformChannelCode: 'Shopify',
		storeId: 1001,
		siteCode: 'US',
		storeName: 'MERACH Official Store',
		orderNo: 'SH2026010803',
		fulfillmentStatus: 'fulfilled',
		orderTime: '2026-01-08 12:00:00',
		skuCode: 'MR-7834W2-US',
		mskuCode: 'MSKU-7834W2',
		quantity: 5,
		productRevenue: 149.95,
		tipRevenue: 10.0,
		postalInsFee: 2.5,
		extendedInsFee: 1.5,
		discount: 15.0,
		shipping: 10.0,
		refund: 0,
		currency: 'USD',
		createTime: '2026-01-08 12:05:00',
	},
	{
		reportId: 4,
		platformChannelCode: 'Shopify',
		storeId: 1003,
		siteCode: 'CA',
		storeName: 'MERACH Canada Store',
		orderNo: 'SH2026010804',
		fulfillmentStatus: 'cancelled',
		orderTime: '2026-01-08 13:30:00',
		skuCode: 'MR-9123B1-CA',
		mskuCode: 'MSKU-9123B1',
		quantity: 3,
		productRevenue: 199.99,
		tipRevenue: 0,
		postalInsFee: 4.0,
		extendedInsFee: 2.5,
		discount: 30.0,
		shipping: 12.0,
		refund: 199.99,
		currency: 'CAD',
		createTime: '2026-01-08 13:35:00',
	},
	{
		reportId: 5,
		platformChannelCode: 'Shopify',
		storeId: 1004,
		siteCode: 'AU',
		storeName: 'MERACH Australia Store',
		orderNo: 'SH2026010805',
		fulfillmentStatus: 'fulfilled',
		orderTime: '2026-01-08 14:45:00',
		skuCode: 'MR-1567P2-AU',
		mskuCode: 'MSKU-1567P2',
		quantity: 1,
		productRevenue: 89.99,
		tipRevenue: 2.5,
		postalInsFee: 3.0,
		extendedInsFee: 1.0,
		discount: 10.0,
		shipping: 8.0,
		refund: 0,
		currency: 'AUD',
		createTime: '2026-01-08 14:50:00',
	},
];
